### PR TITLE
[1.11] Upgrade Quarkus to 1.11.7.Final

### PR DESCRIPTION
**Pull request by Sgitario**

### CODE REVIEW

**Review by pjgg — APPROVED** [review]

**Comment by Sgitario** [comment]
rerun tests

**Comment by pjgg** [comment]
rerun tests

**Comment by Sgitario** [comment]
The OCP 4.6 instance is behaving unstable. Let's try again using the 4.7 instance. Rerun tests.

**Comment by Sgitario** [comment]
The JVM run only failed with one test and it worked after retrying locally.
The Native failures are caused by an OCP too unestable (network instabilities)
Merging this PR.

**Pull request merged**
