### PR TITLE
Default to product coordinates

### PR DESCRIPTION
**Pull request by rsvoboda**
Default to product coordinates, for community coordinates `quarkus-core-only` profile can be used

`quarkus-universe-bom` is only available under `com.redhat.quarkus` groupId for RHBQ

Motivation: We should have consistent way to run the TS on product side (e.g. z-series team, interop testing)

### CODE REVIEW

**Comment by rsvoboda** [comment]
"awesome", [INFO] Quarkus OpenShift TS: Messaging: AMQP with Reactive Messaging FAILURE [ 24.469 s]

Not related to my changes but kills the joy :/

**Comment by Ladicek** [comment]
This is wrong. At the very least, the POM doesn't declare MRRC, so running plain old `mvn clean verify` will most likely fail. (If you have MRRC in your `~/.m2/settings.xml`, you're a tiny minority.)

Second, related to the branching strategy: the `master` branch is for latest upstream/downstream development, yet it forces RHBQ 1.3.4. I have several tests written locally that won't even compile with this setting. At this point, I'm starting to think if branches shouldn't default to the product version, while `master` would default to the latest upstream. WDYT?

**Comment by rsvoboda** [comment]
There are two views on this ... yours and ours :) We use master for product testing (1.3.4 is there because it's the latest public availabe) and we branch once the product is released. This PR make the command used on Jenkins unified for 1.3 and master, this command is used by other teams too (PE for example).

For community bits the default command is `mvn clean verify -Dquarkus-core-only`

**Comment by Ladicek** [comment]
Then the branching strategy you wrote down (copied from Thorntail :-) ) is wrong. And there's no way I can submit my new tests to `master`. We need to figure this out, because Quarkus moves fast and breaking changes are inevitable at this point.

I really think the 1.3 branch must be used for 1.3 testing, otherwise `master` can't contain tests that require 1.4+ and don't compile on 1.3.

**Comment by rsvoboda** [comment]
The trouble is that we moved to `quarkus-universe-bom` and it has different groupId on product side vs. project side.
For `quarkus-bom` there are productized both `io.quarkus` and `com.redhat.quarkus` groupId

**Comment by rsvoboda** [comment]
You can add new test - https://github.com/quarkus-qe/quarkus-openshift-test-suite/blob/master/.github/workflows/ci.yml#L27

**Pull request merged**
