### PR TITLE
custom deployments and messaging cleanup

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by rsvoboda** [comment]
@Ladicek rebase pls

**Comment by Ladicek** [comment]
So far, it was enough to use `@AdditionalResources` to deploy the external application. But if you decide to use `@CustomizeApplicationDeployment` for that (you could e.g. run `oc apply -f .../something.yaml` in this method to deploy the application, instead of putting everything into `src/test/resources/*.yml`), you will need `@CustomizeApplicationUndeployment` (to e.g. run `oc delete -f`).

**Comment by Ladicek** [comment]
Rebased.

**Comment by rsvoboda** [comment]
@mjurc please review and merge if you have no comments

**Pull request merged**
