### PR TITLE
Added session/token expiration scenarios and session revocation(logout)

### PR DESCRIPTION
**Pull request by Sgitario**
This PR updates Code Authorization and Services authorization methods to cover token expiration and session revocation (logout).

### CODE REVIEW

**Comment by Sgitario** [comment]
run tests

**Comment by rsvoboda** [comment]
too many reviewers, keeping Pablo and Michal to check it

**Review by mjurc — APPROVED** [review]
LGTM, thanks for PR

**Comment by Sgitario** [comment]
@pjgg would you mind reviewing this PR? Thanks in advance,

**Review by pjgg — APPROVED** [review]

**Pull request merged**
