### PR TITLE
Update test class names to be unique for Polarion

### PR DESCRIPTION
**Pull request by kshpak**

### CODE REVIEW

**Review by rsvoboda — CHANGES_REQUESTED** [review]
`HttpOpenShiftIT` was missed

**Comment by kshpak** [comment]
@rsvoboda adjusted. Rebuilding CI, as it was failing

**Comment by rsvoboda** [comment]
Jenkins jobs failed, what's the reason for it?

**Comment by kshpak** [comment]
run tests

**Comment by kshpak** [comment]
run tests

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
