### PR TITLE
Upgrade to Quarkus 1.13.2.Final

### PR DESCRIPTION
**Pull request by Sgitario**
Changes:
- Remove workaround of issues/14525
- Changed TODO by comment for issues/15464
- Make sure we use the same gRPC port for running in prod and test (for backward compatibility)

### CODE REVIEW

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
@rsvoboda JVM worked fine, the failures are caused by timeout due to download the artifacts in OpenShift is slow.
I think we're good to merge this PR now.

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
I've updated the external applications modules to increase the timeout to build these apps to 20 minutes.

**Comment by Sgitario** [comment]
run tests

**Comment by rsvoboda** [comment]
CI is not green yet, @Sgitario can you provide tl;dr what's wrong?

**Comment by Sgitario** [comment]
There are some sneaky tests here and there. Now, it failed the kafka avro tests, in other runs, the amqp reactive failed. Everything looks good when running the tests locally.
I fixed the tests about external applications by increasing the timeout to build.
From my point of view, this PR is ready to be merged.

**Comment by rsvoboda** [comment]
So merge and stabilize as we go?

**Comment by Sgitario** [comment]
> So merge and stabilize as we go?

From my point of view, yes. Those failures are not related to Quarkus 1.13.2.Final since have failed in the past too.

**Review by rsvoboda — APPROVED** [review]
Approving for "merge now and stabilise as we go" approach

**Pull request merged**
