### PR TITLE
Multiple Persistence Units 

### PR DESCRIPTION
**Pull request by mjurc**
Adding a test application verifying that configuration of multiple persistence units within application.properties works.

RFE: https://issues.redhat.com/browse/QUARKUS-715

### CODE REVIEW

**Comment by mjurc** [comment]
For the failures analysis, see https://github.com/quarkus-qe/quarkus-openshift-test-suite/pull/212#issuecomment-801743052

**Comment by rsvoboda** [comment]
run tests

**Comment by rsvoboda** [comment]
@mjurc pls rebase

**Comment by rsvoboda** [comment]
to pick https://github.com/quarkus-qe/quarkus-openshift-test-suite/pull/244 changes ...

**Comment by mjurc** [comment]
@rsvoboda Done

**Comment by pjgg** [comment]
LGTM.

**Pull request merged**
