### PR TITLE
GitHub Actions to run surefire tests on merge / PR

### PR DESCRIPTION
**Pull request by rsvoboda**
GitHub Actions to run surefire tests on merge / PR

failsafe (OpenShift cluster) is out of scope of this PR

### CODE REVIEW

**Comment by rsvoboda** [comment]
@Ladicek can you review pls ?

**Comment by Ladicek** [comment]
Ah, one idea: I don't know if it's possible in GitHub Actions, but I've seen others running a temporary OpenShift cluster in CI via `oc cluster up` (which is of course only available for OpenShift 3). On the other hand, the `*OpenShiftIT` tests here are meant to be executed against a real-world-ish cluster, and while the existing ones are small, that doesn't have to be the case all the time. So perhaps we should stick with Surefire-only anyway.

**Comment by rsvoboda** [comment]
crap, I see [ERROR] Non-resolvable import POM: Could not find artifact io.quarkus:quarkus-bom:pom:999-SNAPSHOT @ line 40, column 25

https://github.com/rsvoboda/quarkus-openshift-test-suite/commit/f8ceebd66321339e0ed9b964c6ee9861f23be372/checks?check_suite_id=473332581

**Comment by Ladicek** [comment]
Just wanted to comment about this exact thing. Are we ready for stabilizing on 1.2.1.Final? I'm afraid it doesn't have the fixes for the Kubernetes extension.

**Comment by rsvoboda** [comment]
I will update GH action to build quarkus master

**Pull request merged**
