### PR TITLE
Move import.sql under src/test to avoid duplicate resources being included

### PR DESCRIPTION
**Pull request by rsvoboda**
Move import.sql under src/test to avoid duplicate resources being included

Fixes https://github.com/quarkusio/quarkus/issues/11407 problem for this TS

### CODE REVIEW

**Comment by rsvoboda** [comment]
Native run passed - https://quarkus-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/openshift-test-suite-native-ci/5/

**Comment by Ladicek** [comment]
Does it work? IIRC, it didn't work for me back then.

**Comment by rsvoboda** [comment]
Works with 1.7, did `mvn clean test` locally and all tests passed.
And Jenkins job passed too, executed with `sql-db/app,sql-db/mariadb` modules

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
Cool, thanks. Perhaps they fixed it in the meantime.

**Comment by rsvoboda** [comment]
Messaging tests and GHActions are always trouble :( Not related to this PR, I will make AI to look into it.

**Pull request merged**
