### PR TITLE
[1.11] Update of infinispan-client module tests

### PR DESCRIPTION
**Pull request by mirostary**
Changes are the same as in merged [PR 196](https://github.com/quarkus-qe/quarkus-openshift-test-suite/pull/196)
- An abstract test class that separated test deployment settings and used methods from the actual tests
- Increased Infinispan cluster allocated resources for better stability during restarts
- Second client is copied from the openshift.yml file and deployed with a different name by another YAML file
- 3 more tests for multiple access:
      - simple connect to the second client
      - updating counters
      - connecting back after Datagrid restart

### CODE REVIEW

**Comment by mjurc** [comment]
Run tests

**Comment by rsvoboda** [comment]
@mirostary Changes are not the same as in merged PR 196, please provide the reasoning / adjust the missing parts
 (README / infinispan-client/src/main/resources/META-INF/hotrod-client.properties)

**Comment by rsvoboda** [comment]
CI didn't pass, please investigate what went wrong.

**Comment by mirostary** [comment]
Hi @rsvoboda @mjurc 
I adjusted the missing readme and investigated why the CI is failing. It is because of this issue - https://github.com/quarkusio/quarkus/issues/15487
It is ok in Quarkus version 1.11.6.Final (the commit is reverted in this version), but in 1.11.5.Final this module is failing along with some others modules.

**Comment by rsvoboda** [comment]
Create new commit as part of this PR to move to 1.11.6.Final

**Comment by mirostary** [comment]
Run tests

**Comment by mirostary** [comment]
Run tests

**Comment by rsvoboda** [comment]
@mjurc please do the final check

**Comment by mjurc** [comment]
@mirostary LGTM, I'll merge after https://main-jenkins-csb-quarkusqe.apps.ocp4.prod.psi.redhat.com/job/openshift-test-suite-ci/520/ and https://main-jenkins-csb-quarkusqe.apps.ocp4.prod.psi.redhat.com/job/openshift-test-suite-native-ci/371/ finishes

**Review by mjurc — APPROVED** [review]

**Comment by mjurc** [comment]
CI passed - merging

**Pull request merged**
