### PR TITLE
[1.11] Added lifecycle application module

### PR DESCRIPTION
**Pull request by Sgitario**
Cherry-pick of https://github.com/quarkus-qe/quarkus-openshift-test-suite/pull/239

### CODE REVIEW

**Comment by Sgitario** [comment]
It worked on Native because the way they are handling arguments was working fine. The issue was only on JVM which is failing as expected as we didn't upgrade Quarkus with the fix.

**Comment by pjgg** [comment]
pending to verify against 1.11.7.Final

**Comment by pjgg** [comment]
run test

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
@rsvoboda and @pjgg the tests are now passing so it proves that the latest 1.11.7 release contains the fix. This is ready to be reviewed and merged.

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
