### PR TITLE
Bump Quarkus from 1.12.2.Final to 1.13.0.Final 

### PR DESCRIPTION
**Pull request by rsvoboda**
Bump Quarkus from 1.12.2.Final to 1.13.0.Final

### CODE REVIEW

**Comment by rsvoboda** [comment]
run tests

**Comment by rsvoboda** [comment]
run tests

**Comment by rsvoboda** [comment]
`%test.quarkus.grpc.clients.hello.port=9001` is not needed, causes fail in the run

`[INFO] Quarkus OpenShift TS: Security: Keycloak Authentication + Authorization FAILURE [ 42.302 s]` with master :/

**Review by Sgitario — CHANGES_REQUESTED** [review]
I disagree about having the property `quarkus.grpc.clients.hello.port` as global property as it is only needed on modules having a `hello` grpc service.

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
Upgrade will be done as part of https://github.com/quarkus-qe/quarkus-openshift-test-suite/pull/266. Closing.

**Pull request closed without merging**
