### PR TITLE
OpenShift Serverless support in test framework, first test for OpenShift Serverless

### PR DESCRIPTION
**Pull request by rsvoboda**
OpenShift Serverless support in test framework, first test for OpenShift Serverless

See changes in README.md

Went ahead with dedicated profile because `@OnlyIfConfigured("ts.serverless")` approach wouldn't prevent execution of the S2I build during the `package` phase.

### CODE REVIEW

**Comment by Ladicek** [comment]
This looks pretty good, but reveals a design mistake I made when introducing `@ManualApplicationDeployment`. This annotation conflates 2 things: intent to deploy the application manually, and source of application metadata when the `app-metadata` Quarkus extension is not present. As you just found, sometimes we want to deploy the application manually, yet we don't need to provide app metadata explicitly, because the application source is in the test suite and has the `app-metadata` extension.

This really should be 2 different annotations: `@ManualApplicationDeployment` would just state "I'll deploy the app manually" and would have no attributes, and something like `@ExplicitAppMetadata` would have all the attributes and would only be used if `app-metadata` is not present.

If you wish, I can do the refactoring.

**Comment by Ladicek** [comment]
Here it is: https://github.com/Ladicek/quarkus-openshift-test-suite/commits/serverless

**Comment by Ladicek** [comment]
I can force-push to your branch (to change this PR), if you agree.

**Comment by rsvoboda** [comment]
@Ladicek agree, please proceed

**Comment by Ladicek** [comment]
Done :-)

**Comment by rsvoboda** [comment]
+1 for the changes you did

**Comment by Ladicek** [comment]
Thanks :-) Not sure why the messaging test failed, but perhaps we should invoke Maven with `-fae` in the CI actions.

**Comment by rsvoboda** [comment]
messaging test fails from time to time on GH actions :( Have AI to look into it.

**Pull request merged**
