### PR TITLE
Sort and remove unused imports during the build

### PR DESCRIPTION
**Pull request by rsvoboda**
Sort and remove unused imports during the build

Look at pom.xml changes, the rest was produced by `mvn clean install -DskipTests -DskipITs`

### CODE REVIEW

**Comment by Ladicek** [comment]
This is good, but the style totally has to match what IntelliJ does :-) Unfortunately, it isn't 100% possible, but it's easy to get very close. I'll push to this PR and merge.

**Comment by rsvoboda** [comment]
Quarkus is using "wrong" setup too ?

https://github.com/quarkusio/quarkus/blob/master/build-parent/pom.xml#L379-L389

**Comment by Ladicek** [comment]
Yes.

**Comment by Ladicek** [comment]
Thanks! :-)

**Comment by rsvoboda** [comment]
Welcome ;)

**Pull request merged**
